### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by bitcometz** [nitzanlab/biolord#10]
### Report

Hello, thanks for this great tool.
After I have installed this tool with 'pip install biolord'

Then, I try: 
```
import pandas as pd
import numpy as np

import scanpy as sc
import biolord

import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from scipy.stats import ttest_rel
```

I got the errors:
```
TypeError                                 Traceback (most recent call last)
Cell In[2], line 5
      2 import numpy as np
      4 import scanpy as sc
----> 5 import biolord
      7 import seaborn as sns
      8 import matplotlib.pyplot as plt

... ...
File /path/biolord/lib/python3.8/site-packages/optax/contrib/dadapt_adamw.py:45
     39   numerator_weighted: chex.Array  # shape=(), dtype=jnp.float32.
     40   count: chex.Array  # shape=(), dtype=jnp.int32.
     43 def dadapt_adamw(
     44     learning_rate: base.ScalarOrSchedule = 1.0,
---> 45     betas: tuple[float, float] = (0.9, 0.999),
     46     eps: float = 1e-8,
     47     estim_lr0: float = 1e-6,
     48     weight_decay: float = 0.,
     49 ) -> base.GradientTransformation:
     50   """Learning rate free AdamW by D-Adaptation.
     51 
     52   Adapts the baseline learning rate of AdamW automatically by estimating the
   (...)
     69     A `GradientTransformation` object.
     70   """
     72   def init_fn(params: base.Params) -> DAdaptAdamWState:

TypeError: 'type' object is not subscriptable

```

Could you please help with this problem?
Thanks !!!

### Version information

$ pip list
Package                   Version
------------------------- ---------------
absl-py                   2.1.0
aiohttp                   3.9.3
aiosignal                 1.3.1
anndata                   0.9.2
anyio                     4.2.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
async-timeout             4.0.3
attrs                     23.2.0
Babel                     2.14.0
backcall                  0.2.0
beautifulsoup4            4.12.3
biolord                   0.0.2
bleach                    6.1.0
cached-property           1.5.2
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
chex                      0.1.7
comm                      0.2.1
contextlib2               21.6.0
contourpy                 1.1.1
cycler                    0.12.1
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
dm-tree                   0.1.8
docrep                    0.3.2
et-xmlfile                1.1.0
etils                     1.3.0
exceptiongroup            1.2.0
executing                 2.0.1
fastjsonschema            2.19.1
filelock                  3.13.1
flax                      0.7.2
fonttools                 4.47.2
fqdn                      1.5.1
frozenlist                1.4.1
fsspec                    2024.2.0
get-annotations           0.1.2
h11                       0.14.0
h5py                      3.10.0
httpcore                  1.0.2
httpx                     0.26.0
idna                      3.6
importlib-metadata        7.0.1
importlib-resources       6.1.1
ipykernel                 6.29.0
ipython                   8.12.3
ipywidgets                8.1.1
isoduration               20.11.0
jax                       0.4.13
jaxlib                    0.4.13
jedi                      0.19.1
Jinja2                    3.1.3
joblib                    1.3.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.0
jupyter-console           6.6.3
jupyter_core              5.7.1
jupyter-events            0.9.0
jupyter-lsp               2.2.2
jupyter_server            2.12.5
jupyter_server_terminals  0.5.2
jupyterlab                4.1.0
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.2
jupyterlab-widgets        3.0.9
kiwisolver                1.4.5
lightning-utilities       0.10.1
llvmlite                  0.41.1
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.7.4
matplotlib-inline         0.1.6
mdurl                     0.1.2
mistune                   3.0.2
ml_collections            0.1.1
ml-dtypes                 0.2.0
mpmath                    1.3.0
msgpack                   1.0.7
mudata                    0.2.3
multidict                 6.0.5
multipledispatch          1.0.0
natsort                   8.4.0
nbclient                  0.9.0
nbconvert                 7.14.2
nbformat                  5.9.2
nest-asyncio              1.6.0
networkx                  3.1
notebook                  7.0.7
notebook_shim             0.2.3
numba                     0.58.1
numpy                     1.24.4
numpyro                   0.12.1
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
openpyxl                  3.1.2
opt-einsum                3.3.0
optax                     0.1.8
orbax-checkpoint          0.2.3
overrides                 7.7.0
packaging                 23.2
pandas                    2.0.3
pandocfilters             1.5.1
parso                     0.8.3
patsy                     0.5.6
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    10.2.0
pip                       24.0
pkgutil_resolve_name      1.3.10
platformdirs              4.2.0
prometheus-client         0.19.0
prompt-toolkit            3.0.43
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.17.2
pynndescent               0.5.11
pyparsing                 3.1.1
pyro-api                  0.1.2
pyro-ppl                  1.8.6
python-dateutil           2.8.2
python-json-logger        2.0.7
pytorch-lightning         1.9.5
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     25.1.2
qtconsole                 5.5.1
QtPy                      2.4.1
referencing               0.33.0
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.0
rpds-py                   0.17.1
scanpy                    1.9.8
scikit-learn              1.3.2
scipy                     1.10.1
scvi-tools                0.20.3
seaborn                   0.13.2
Send2Trash                1.8.2
session-info              1.0.0
setuptools                69.0.3
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.6.3
statsmodels               0.14.1
stdlib-list               0.10.0
sympy                     1.12
tensorstore               0.1.45
terminado                 0.18.0
threadpoolctl             3.2.0
tinycss2                  1.2.1
tomli                     2.0.1
toolz                     0.12.1
torch                     2.2.0
torchmetrics              1.3.0.post0
tornado                   6.4
tqdm                      4.66.1
traitlets                 5.14.1
triton                    2.2.0
types-python-dateutil     2.8.19.20240106
typing_extensions         4.9.0
tzdata                    2023.4
umap-learn                0.5.5
uri-template              1.3.0
urllib3                   2.2.0
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.7.0
wheel                     0.42.0
widgetsnbextension        4.0.9
yarl                      1.9.4
zipp                      3.17.0

**Comment by yczju** [comment]
> Hi! thank you for using biolord. The issue you encountered is raised by the `optax` package and addressed here [#711](https://github.com/google-deepmind/optax/issues/711). As suggested you may try downgrading to optax 0.1.7 or consider moving to python > 3.8.

Hello, thanks for your wonderful work! I found this problem still exists after I use python==3.9 and optax==0.1.7.

After running `import biolord`
I got the error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 import biolord

File ~/anaconda3/envs/biolord/lib/python3.8/site-packages/biolord/__init__.py:2
      1 from . import _utils as ul
----> 2 from ._model import Biolord
      3 from ._module import BiolordClassifyModule, BiolordModule
      5 __all__ = ["Biolord", "BiolordModule", "BiolordClassifyModule"]

File ~/anaconda3/envs/biolord/lib/python3.8/site-packages/biolord/_model.py:29
     26 from tqdm import tqdm
     28 from ._data import AnnDataSplitter
---> 29 from ._module import BiolordClassifyModule, BiolordModule
     30 from ._train import biolordClassifyTrainingPlan, biolordTrainingPlan
     31 from ._utils import repeat_n

File ~/anaconda3/envs/biolord/lib/python3.8/site-packages/biolord/_module.py:49
     45         x_ = x_ * self.embed
     46         return x_
---> 49 class BiolordModule(BaseModuleClass):
     50     """The :mod:`biolord` module.
     51 
     52     Parameters
...
    132     ):
    133         super().__init__()
    134         gene_likelihood = gene_likelihood.lower()

TypeError: 'type' object is not subscriptable
```


Package version:
Package                      Version
---------------------------- ----------
absl-py                      2.0.0
aiofiles                     22.1.0
aiohttp                      3.9.1
aiosignal                    1.3.1
aiosqlite                    0.19.0
anndata                      0.9.1
anyio                        3.6.2
appdirs                      1.4.4
arcgis                       2.1.0.3
archspec                     0.2.2
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
arrow                        1.2.3
asttokens                    2.2.1
astunparse                   1.6.3
async-timeout                4.0.3
attrs                        23.1.0
audioread                    3.0.1
autogenes                    1.0.4
Babel                        2.13.1
backcall                     0.2.0
beautifulsoup4               4.12.2
biolord                      0.0.3
biothings-client             0.3.1
bleach                       6.0.0
boltons                      23.1.1
Brotli                       1.1.0
cached-property              1.5.2
cachetools                   5.3.2
certifi                      2024.2.2
cffi                         1.16.0
charset-normalizer           3.3.2
chex                         0.1.7
click                        8.1.3
cloudpickle                  3.0.0
cmake                        3.26.3
colorama                     0.4.6
combat                       0.3.3
comm                         0.1.3
conda                        23.11.0
conda-libmamba-solver        23.12.0
conda-package-handling       2.2.0
conda_package_streaming      0.9.0
contextlib2                  21.6.0
contourpy                    1.0.7
cryptography                 41.0.7
cycler                       0.11.0
Cython                       3.0.6
dask                         2023.5.0
deap                         1.4.1
debugpy                      1.6.7
decorator                    5.1.1
defusedxml                   0.7.1
dill                         0.3.7
distro                       1.9.0
dm-tree                      0.1.8
docker-pycreds               0.4.0
docrep                       0.3.2
dominate                     2.7.0
et-xmlfile                   1.1.0
etils                        1.3.0
executing                    1.2.0
fastjsonschema               2.16.3
filelock                     3.12.0
flatbuffers                  23.5.26
flax                         0.7.2
fonttools                    4.39.3
fqdn                         1.5.1
frozenlist                   1.4.1
fsspec                       2023.10.0
gast                         0.4.0
geomet                       1.1.0
gitdb                        4.0.10
GitPython                    3.1.31
google-auth                  2.23.3
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
GPUtil                       1.4.0
graphviz                     0.20.1
grpcio                       1.59.0
gssapi                       1.8.3
h5py                         3.8.0
huggingface-hub              0.18.0
hypertools                   0.8.0
idna                         3.6
imageio                      2.28.1
importlib-metadata           6.6.0
importlib-resources          5.12.0
intel-openmp                 2024.0.2
ipykernel                    6.22.0
ipython                      8.12.0
ipython-genutils             0.2.0
ipywidgets                   8.0.6
isoduration                  20.11.0
jaraco.classes               3.3.0
jax                          0.4.13
jaxlib                       0.4.13
jedi                         0.18.2
jeepney                      0.8.0
Jinja2                       3.1.2
joblib                       1.2.0
json5                        0.9.14
jsonpatch                    1.32
jsonpointer                  2.3
jsonschema                   4.20.0
jsonschema-specifications    2023.11.2
jupyter                      1.0.0
jupyter-client               6.1.12
jupyter-console              6.6.3
jupyter_core                 5.3.0
jupyter-events               0.6.3
jupyter-server               1.24.0
jupyter_server_fileid        0.9.0
jupyter_server_terminals     0.4.4
jupyter_server_ydoc          0.8.0
jupyter-ydoc                 0.2.5
jupyterlab                   3.6.6
jupyterlab-pygments          0.2.2
jupyterlab_server            2.25.2
jupyterlab-widgets           3.0.7
kaleido                      0.2.1
keras                        2.13.1
Keras-Preprocessing          1.1.2
keyring                      24.3.0
kiwisolver                   1.4.4
lazy_loader                  0.2
lerc                         4.0.1
libclang                     16.0.6
libmambapy                   1.5.6
librosa                      0.10.1
lightning                    2.2.1
lightning-utilities          0.10.0
lit                          16.0.1
llvmlite                     0.40.0
locket                       1.0.0
loompy                       3.0.7
lxml                         4.9.3
mamba                        1.5.6
Markdown                     3.5
markdown-it-py               3.0.0
MarkupSafe                   2.1.2
matplotlib                   3.7.1
matplotlib-inline            0.1.6
mdurl                        0.1.2
menuinst                     2.0.2
mistune                      2.0.5
mkl                          2024.0.0
ml-collections               0.1.1
ml-dtypes                    0.2.0
more-itertools               10.1.0
mpmath                       1.3.0
msgpack                      1.0.7
mudata                       0.2.3
multidict                    6.0.4
multipledispatch             1.0.0
mygene                       3.2.2
natsort                      8.3.1
nbclassic                    1.0.0
nbclient                     0.7.4
nbconvert                    7.3.1
nbformat                     5.8.0
nest-asyncio                 1.5.6
networkx                     3.1
ninja                        1.11.1.1
notebook                     6.5.4
notebook_shim                0.2.3
numba                        0.57.0
numpy                        1.23.5
numpy-groupies               0.9.22
numpyro                      0.12.1
nvidia-cublas-cu11           11.10.3.66
nvidia-cuda-cupti-cu11       11.7.101
nvidia-cuda-nvrtc-cu11       11.7.99
nvidia-cuda-runtime-cu11     11.7.99
nvidia-cudnn-cu11            8.5.0.96
nvidia-cufft-cu11            10.9.0.58
nvidia-curand-cu11           10.2.10.91
nvidia-cusolver-cu11         11.4.0.1
nvidia-cusparse-cu11         11.7.4.91
nvidia-nccl-cu11             2.14.3
nvidia-nvtx-cu11             11.7.91
oauthlib                     3.2.2
openpyxl                     3.1.2
opt-einsum                   3.3.0
optax                        0.1.7
orbax-checkpoint             0.2.3
packaging                    23.1
pandas                       2.0.1
pandocfilters                1.5.0
parso                        0.8.3
partd                        1.4.1
pathtools                    0.1.2
patsy                        0.5.3
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       9.5.0
pip                          23.3.2
pkgutil_resolve_name         1.3.10
platformdirs                 3.5.0
plotly                       5.18.0
pluggy                       1.4.0
pooch                        1.8.0
ppca                         0.0.4
prometheus-client            0.16.0
prompt-toolkit               3.0.38
protobuf                     4.22.3
psutil                       5.9.5
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycosat                      0.6.6
pycparser                    2.21
pydot                        1.4.2
Pygments                     2.15.1
pynndescent                  0.5.10
pyparsing                    3.0.9
pyro-api                     0.1.2
pyro-ppl                     1.8.6
pyrsistent                   0.19.3
pyshp                        2.3.1
PySocks                      1.7.1
python-certifi-win32         1.6.1
python-dateutil              2.8.2
python-json-logger           2.0.7
pytorch-lightning            1.9.5
pytz                         2023.3
PyVCF                        0.6.8
PyWavelets                   1.4.1
pyworld                      0.2.12
PyYAML                       6.0
pyzmq                        19.0.2
qnorm                        0.8.1
qtconsole                    5.4.3
QtPy                         2.3.1
radian                       0.6.9
rchitect                     0.4.6
referencing                  0.31.1
requests                     2.31.0
requests-gssapi              1.2.3
requests-oauthlib            1.3.1
requests-toolbelt            1.0.0
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rich                         13.7.0
rpds-py                      0.13.2
rsa                          4.9
ruamel.yaml                  0.18.5
ruamel.yaml.clib             0.2.7
safetensors                  0.4.0
scanpy                       1.9.3
scikit-image                 0.20.0
scikit-learn                 1.2.2
scipy                        1.9.1
scvelo                       0.3.1
scvi-tools                   0.20.3
seaborn                      0.12.2
SecretStorage                3.3.3
Send2Trash                   1.8.2
sentry-sdk                   1.20.0
session-info                 1.0.0
setproctitle                 1.3.2
setuptools                   69.0.3
setuptools-scm               8.0.4
six                          1.16.0
smmap                        5.0.0
sniffio                      1.3.0
soundfile                    0.12.1
soupsieve                    2.4.1
soxr                         0.3.7
stack-data                   0.6.2
statsmodels                  0.14.0
stdlib-list                  0.8.0
sympy                        1.11.1
tbb                          2021.11.0
tenacity                     8.2.3
tensorboard                  2.13.0
tensorboard-data-server      0.7.2
tensorflow                   2.13.1
tensorflow-estimator         2.13.0
tensorflow-io-gcs-filesystem 0.34.0
tensorstore                  0.1.45
termcolor                    2.3.0
terminado                    0.17.1
threadpoolctl                3.1.0
tifffile                     2023.4.12
tim                          0.3
timm                         0.3.2
tinycss2                     1.2.1
tomli                        2.0.1
toolz                        0.12.0
torch                        2.0.0
torch-tb-profiler            0.4.3
torchmetrics                 1.2.1
torchvision                  0.15.1
torchviz                     0.0.2
tornado                      6.3.1
tqdm                         4.65.0
traitlets                    5.9.0
triton                       2.0.0
typing_extensions            4.9.0
tzdata                       2023.3
ujson                        5.8.0
umap-learn                   0.5.3
uri-template                 1.2.0
urllib3                      2.1.0
visdom                       0.2.4
wandb                        0.15.0
wcwidth                      0.2.13
webcolors                    1.13
webencodings                 0.5.1
websocket-client             1.5.1
Werkzeug                     3.0.1
wheel                        0.42.0
widgetsnbextension           4.0.7
wrapt                        1.15.0
xmltodict                    0.13.0
y-py                         0.6.2
yarl                         1.9.4
ypy-websocket                0.8.4
zipp                         3.15.0
zstandard                    0.22.0


Could you please help to solve the problem?  Thanks a lot!

**Comment by zoepiran** [comment]
Hi, 

according to the error it seems like you are using python==3.8. 

`File ~/anaconda3/envs/biolord/lib/python3.8/site-packages/biolord/__init__.py:2`

**Comment by yczju** [comment]
> Hi,
> 
> according to the error it seems like you are using python==3.8.
> 
> `File ~/anaconda3/envs/biolord/lib/python3.8/site-packages/biolord/__init__.py:2`

Thanks a lot! It works.
