### ISSUE TITLE
adata_preds variable is not defined in omics tutorial 

### ISSUE THREAD

**Issue by Arkkienkeli** [nitzanlab/biolord#13]
### Report

In **Using [biolord](https://biolord.readthedocs.io/en/latest/api.html#module-biolord) for -omics data** tutorial in *Studying relations between attributes* section, `adata_preds` is not defined.

**Comment by zoepiran** [comment]
Thank you for spotting this!  
Those were irrelevant cells that were there accidentally there--please excuse us. 
We have just pushed a fix.

We will soon update the documentation and add tutorials including additional analysis applications enabled by biolord.
Meanwhile, in case you are interested in the prediction module here is an illustration that may be useful:
 
<img width="1777" alt="cp_illustration" src="https://github.com/nitzanlab/biolord/assets/43661890/75a4d21c-06b9-4f4f-9fee-3336b29cdf4a">

**Comment by Arkkienkeli** [comment]
Thank you for a very quick fix!
