### ISSUE TITLE
Hyperparameters for gene_likelihood='nb'

### ISSUE THREAD

**Issue by ArianAmani** [nitzanlab/biolord#16]
### Report

Hi,
I am trying to use Biolord for some benchmarking and use it on different datasets. I am using the default parameters provided in the tutorials in your [docs](https://biolord.readthedocs.io/en/latest/tutorials/biolord_pipeline.html), although I plan to use counts and therefore, `gene_likelihood='nb'` instead of `normal` which is used in the tutorials. So the `gene_likelihood='nb'` is the only change I made to the default hyperparameters used in the tutorial notebooks.

The latent UMAPs from the trained model using this setting looked a bit odd to me, therefore I wanted to ask you if they seem fine, and if not, ask if you have any suggestions for what hyperparameters I can use to get the best results using  `gene_likelihood='nb'`.

To give more details, I am using a dataset of ~200K cells with 1212 HVGs and 5 covariates as input. 
UMAPs of each latent for the whole dataset:
Each umap is colored by the name above it:

Z_0:
![image](https://github.com/nitzanlab/biolord/assets/78699446/049a3b4d-3ddf-4fbe-bc64-58a68725f539)

Z_tissue:
![image](https://github.com/nitzanlab/biolord/assets/78699446/989ee03e-50ce-4839-9f89-8e66389dee36)

Z_sampleID:
![image](https://github.com/nitzanlab/biolord/assets/78699446/3d8a5594-e9cb-4740-a2df-3734641c13e6)

Z_sex:
![image](https://github.com/nitzanlab/biolord/assets/78699446/8fa67116-aa5a-424c-abe8-e43c67dbfefc)

Z_ageBin:
![image](https://github.com/nitzanlab/biolord/assets/78699446/09f47468-577e-4eb8-ad47-bb8aa1766d5c)

Z_cellType:
![image](https://github.com/nitzanlab/biolord/assets/78699446/a5e2b43b-db31-46be-a54e-4c384cc18ae9)

**To me, as mentioned above, the shadow effect of some cells in all the umaps, seems a bit odd, this part:**
![image](https://github.com/nitzanlab/biolord/assets/78699446/ddbe3382-d60d-43fd-b29e-c64d28746383)

So I wanted to check with you if this is something that I should be worried about, it makes sense, or it doesn't, and generally what is your suggestion for training/hyperparameters to achieve best results using your model.

Here is also a link to a notebook, containing the training and inference code I am using:
[Google Colab Notebook](https://drive.google.com/file/d/1RTsZJ-bUwKY_OvOCVzDgqB8jV10eZNrN/view?usp=sharing
)

Best,
Arian

* Also I am using the Biolord version `0.0.2`. (for environment dependency reasons)

```
>>> session_info.show(html=False, dependencies=True)
-----
biolord             0.0.2
session_info        1.0.0
-----
PIL                         10.3.0
absl                        NA
anndata                     0.10.7
arrow                       1.3.0
attr                        23.2.0
attrs                       23.2.0
brotli                      1.0.9
certifi                     2024.06.02
cffi                        1.16.0
charset_normalizer          3.3.2
chex                        0.1.86
click                       8.1.7
cloudpickle                 3.0.0
colorama                    0.4.6
contextlib2                 NA
cupy                        13.1.0
cupy_backends               NA
cupyx                       NA
cycler                      0.12.1
cython_runtime              NA
dask                        2024.1.1
dateutil                    2.9.0.post0
defusedxml                  0.7.1
dockerpycreds               NA
docrep                      0.3.2
etils                       1.5.2
exceptiongroup              1.2.1
fastrlock                   0.8.2
filelock                    3.14.0
flax                        0.8.3
fqdn                        NA
fsspec                      2024.3.1
git                         3.1.43
gitdb                       4.0.11
gmpy2                       2.1.2
google                      NA
h5py                        3.11.0
idna                        3.7
igraph                      0.11.5
importlib_metadata          NA
importlib_resources         NA
iniconfig                   NA
isoduration                 NA
jax                         0.4.23
jaxlib                      0.4.23
jinja2                      3.1.4
joblib                      1.4.2
jsonpointer                 2.4
jsonschema                  4.22.0
jsonschema_specifications   NA
kiwisolver                  1.4.5
legacy_api_wrap             NA
leidenalg                   0.10.2
lightning_fabric            1.9.5
lightning_utilities         0.11.2
llvmlite                    0.42.0
markupsafe                  2.1.5
matplotlib                  3.8.4
ml_collections              NA
ml_dtypes                   0.4.0
mpl_toolkits                NA
mpmath                      1.3.0
msgpack                     1.0.8
mudata                      0.2.3
multipledispatch            0.6.0
natsort                     8.4.0
numba                       0.59.1
numpy                       1.26.4
numpyro                     0.14.0
opt_einsum                  v3.3.0
optax                       0.2.2
packaging                   24.0
pandas                      2.2.1
pkg_resources               NA
platformdirs                4.2.2
pluggy                      1.5.0
pretty_errors               1.2.25
prometheus_client           NA
psutil                      5.9.8
py                          NA
pyarrow                     14.0.2
pydot                       2.0.0
pygments                    2.18.0
pynvml                      11.4.1
pyparsing                   3.1.2
pyro                        1.9.0
pytest                      8.2.0
pytorch_lightning           1.9.5
pytz                        2024.1
rapids_dask_dependency      NA
ray                         2.9.3
referencing                 NA
requests                    2.31.0
rfc3339_validator           0.1.4
rfc3986_validator           0.1.1
rich                        NA
rpds                        NA
scanpy                      1.10.1
scipy                       1.12.0
scvi                        0.20.3
sentry_sdk                  2.1.1
setproctitle                1.2.2
setuptools                  69.5.1
setuptools_scm              NA
six                         1.16.0
sklearn                     1.4.2
smmap                       5.0.1
socks                       1.7.1
sympy                       1.12.1
tblib                       3.0.0
texttable                   1.7.0
threadpoolctl               3.5.0
tlz                         0.12.1
toolz                       0.12.1
torch                       2.1.2+cu121
torchgen                    NA
torchmetrics                1.4.0
torchvision                 0.16.2
tqdm                        4.66.4
typing_extensions           NA
uri_template                NA
urllib3                     2.2.1
uvloop                      0.19.0
wandb                       0.17.0
wandb_gql                   NA
wandb_graphql               1.1
wandb_promise               2.3
wandb_watchdog              NA
wcwidth                     0.2.13
webcolors                   1.13
yaml                        6.0.1
zipp                        NA
zoneinfo                    NA
-----
Python 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0]
Linux-5.15.0-112-generic-x86_64-with-glibc2.35
-----
Session information updated at 2024-07-04 22:14
```

**Comment by zoepiran** [comment]
Dear Arian,

Thank you for reaching out, we are excited to see that you are applying _biolord_ in your benchmarks.
First of all i must say i find these results very promising!

Lets understand what we are seeing here, starting from the first panel, the umap based on the `unknown_attributes_latent` latent vector. Ideally, when sufficiently informative `known_attributes` are provided the  `unknown_attributes_latent` shall only capture background/noise and should not encode meaningful  biological signal. Hence, the appearance of a global blob there, and no clear separation of the data is great (!). 

With that, I am not sure what is the source of the _shadow_ effect, it could be very interesting to identify these cells (can be done naively by coordinates in the umap or via clustering or umap density) and look into them, initially maybe coloring over a umap of the original data. One can further look into correlations between the classification/distance from the blob center and features of the data.

Next, in each of the subsequent panels we are looking at the embedding based on `unknown_attributes_latent` + `latent_{cat}` for the cat's you defined. Recall,  for a given category `known_attribute`, `cat` all cells with the same label will share `latent_{cat}`, thus, for example in the `sex`, this will reduce to two points in space, then around these points, we are just observing the spread induced by the `unknown_attributes_latent` (the `unknown_attributes_latent` is the only latent which is distinct for each cell in the data). 

I would like to highlight that we suggest a different approach to study the latent space, focusing on the _discrete_ limited space of each `known_attribute` we look into the relationships between them, as provided in the example [Using `biolord` for -omics data](https://biolord.readthedocs.io/en/latest/tutorials/biolord_omics.html#using-biolord-for-omics-data), section ["Explore the latent space"](https://biolord.readthedocs.io/en/latest/tutorials/biolord_omics.html#explore-the-latent-space). 
Here we construct vectors which are concatenations of the different possible combinations of the `known_attributes` in the data and visualize them in a lower dimensional space. 

At last, regarding training you could consider disabling the `early_stopping` and training for longer.
I hope this was helpful, feel free to reach out for any additional clarifications.
