### ISSUE TITLE
data preprocessing question

### ISSUE THREAD

**Issue by szalata** [nitzanlab/biolord#18]
Hello,
I cannot find the details on the recommended data preprocessing for working on logarithmized data. Do you normalize counts per cell? Is it 
```
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
```

**Comment by zoepiran** [comment]
Preprocessing depends on the `layer` and `gene_likelihood`, shall you wish to model the data as a Negative Binomial (`"nb"`) no normalization is done and you should use `counts`. If data is normalized use `"normal"`.

**Comment by szalata** [comment]
Thank you for the quick answer! My question only refers to the log normalized data with "normal" gene_likelihood. Do you normalize counts per cell before log-normalization then?
```
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
```

**Comment by zoepiran** [comment]
yes :)
