### ISSUE TITLE
About unseen counterfactuals

### ISSUE THREAD

**Issue by nrclaudio** [nitzanlab/biolord#19]
Hi,

How do you perform counterfactuals on unseen attributes (as in sciplex in your paper) in practice? From the methods section, you mention that you use dosage and chemically informed embeddings as ordered attributes. The dosage is clear in this case, but how do you use an embedding as input? 

Best,

Claudio

**Comment by zoepiran** [comment]
Hi Claudio,

Thank you for reaching out!
I believe the reproducibility repository can be useful to see the complete code. Specifically in [1_perturbations_sciplex3_preprocessing.ipynb](https://github.com/nitzanlab/biolord_reproducibility/blob/main/notebooks/perturbations/sciplex3/1_perturbations_sciplex3_preprocessing.ipynb) you will see one possibility for drugs embedding based in Rdkit. 
The embeddings are stored in `.obsm["rdkit2d_dose"]`. Next, as you can see in [2_perturbations_sciplex3_evaluation.ipynb](https://github.com/nitzanlab/biolord_reproducibility/blob/main/notebooks/perturbations/sciplex3/2_perturbations_sciplex3_evaluation.ipynb) they are passed as input to `setup_anndata()` via the `ordered_attributes_keys` param.

Hope this helps,
Zoe
